import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..", "..");
const outDir = resolve(__dirname, "..", "src", "generated");

const TOPICS = ["api", "features", "configuration", "troubleshooting"];

const entries = TOPICS.map((topic) => {
  const filePath = resolve(repoRoot, "docs", `${topic}.md`);
  const content = readFileSync(filePath, "utf8");
  const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
  return `  ${JSON.stringify(topic)}: \`${escaped}\``;
});

const output = `// Auto-generated by scripts/embed-docs.js — do not edit manually.
export const PONCHO_DOCS: Record<string, string> = {
${entries.join(",\n")},
};
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, "poncho-docs.ts"), output, "utf8");
console.log(`[embed-docs] Generated poncho-docs.ts with ${TOPICS.length} topics`);
